### PR TITLE
Creates API url by hukamnama date

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**

### CODE REVIEW

**Comment by bogas04** [comment]
Can you bump the version? `npm version minor`

**Comment by Gauravjeetsingh** [comment]
Done @bogas04 ji

**Comment by bogas04** [comment]
Published `@sttm/banidb@2.1.0`

**Comment by bogas04** [comment]
Invited you as well @Gauravjeetsingh.

**Comment by bogas04** [comment]
Had to republish as `@sttm/banidb@2.1.1` due to outdated build file.

**Pull request merged**
