### PR TITLE
use v2 api url

### PR DESCRIPTION
**Pull request by AkalUstat**

### CODE REVIEW

**Comment by navdeepsinghkhalsa** [comment]
Heads-up: Introducing the v2 URL is a breaking change and would require a bump in the major version (i.e. 3.0.0)

**Comment by ManjotS** [comment]
It is already broken. V1 was taken offline some time ago.

**Comment by navdeepsinghkhalsa** [comment]
@ManjotS Sorry - I should clarify that it's a change to the API of the module that is incompatible with the previous version. Any developer using the module would be required to rework their script because of this change, regardless of whether or not the v1 banidb-api was up or down. Because we follow Semantic Versioning, it would require a major version bump.

**Comment by AkalUstat** [comment]
any other breaking changes we wanna make since we already bumping up the version @navdeepsinghkhalsa

**Comment by navdeepsinghkhalsa** [comment]
I think just making sure that it's 1-to-1 with the current v2 spec.

**Comment by navdeepsinghkhalsa** [comment]
Once GraphQL is done on the API, it could be added to this as a 3.1

**Comment by AkalUstat** [comment]
@ManjotS all the options for url are uptodate right?

**Comment by AkalUstat** [comment]
@navdeepsinghkhalsa looks like this is all thats needed for now if graphql will be handled later

**Comment by AkalUstat** [comment]
Bump @ManjotS

**Pull request merged**
