### PR TITLE
Changes API url to be compatible with v2

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@bogas04 @navdeepsinghkhalsa Can you please take a look into this? I checked the API URLs from the routes files of banidb-api

**Comment by bogas04** [comment]
This would be a breaking change as the responses would be different. We need to make a major version bump for this.

**Comment by Gauravjeetsingh** [comment]
@bogas04 
So, should I just change the version in package.json? :wink: 
Are there any other changes we want to do before doing a version bump?

**Comment by bogas04** [comment]
Yes just bump the version, I or @navdeepsinghkhalsa can publish it. If you share your npm handle i can add you as a collaborator there as well.

**Comment by Gauravjeetsingh** [comment]
@bogas04 ji updated the version. let me know when you publish it.
cc: @navdeepsinghkhalsa

**Comment by Gauravjeetsingh** [comment]
My npmjs handle is : turbanpanda

**Comment by bogas04** [comment]
Please update package-lock as well for version. Use `n version 1.2.0`

**Comment by Gauravjeetsingh** [comment]
@bogas04 Done

**Comment by bogas04** [comment]
I've published the same.

https://www.npmjs.com/package/@sttm/banidb

**Pull request merged**
