### PR TITLE
added search types 5-7 (not sure how ang was working before in web)

### PR DESCRIPTION
**Pull request by ManjotS**

### CODE REVIEW

**Comment by ManjotS** [comment]
@tsingh777 please merge and deploy to npm after approval

**Comment by ManjotS** [comment]
next npm version should be 1.0.2

**Comment by tsingh777** [comment]
Its on 2.2.3 https://www.npmjs.com/package/@sttm/banidb

**Comment by ManjotS** [comment]
Ok let's just increment and deploy

**Comment by Gauravjeetsingh** [comment]
Ang was manually added to types in sttm-web. Just checked. I will get rid of it once this update is ready to be used in web.

**Pull request merged**
